# Generated by Django 3.2.7 on 2021-09-26 12:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date_of_completion', models.DateTimeField()),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'New'), (1, 'Complete')], default=0)),
                ('date_of_creation', models.DateTimeField(auto_now_add=True)),
                ('date_of_modification', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(check=models.Q(('date_of_completion__gt', django.db.models.expressions.F('date_of_creation'))), name='mycustomconstraint_checktime1'),
        ),
    ]
